groups:
  - name: NewCriticalDevice
    rules:
      - alert: CriticalDevice 
        expr: sum by (serial_number, device_type) (device_health{group="critical"})
        annotations:
          serial_number: "{{ $labels.serial_number }}"
          device_type: "{{ $labels.device_type }}"


