groups:
  - name: NewCriticalDevice
    rules:
      - alert: CriticalDevice 
        expr: sum by (serial_number, device_type) (device_health{group="critical"})
        labels:
          severity: low
        annotations:
          summary: 'Testing...'
