route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 1h
  receiver: 'mail'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
templates: 
  - '/alert_manager/*.tmpl'
receivers:
  - name: 'mail'
    email_configs:
      - require_tls: false
        headers: 
          subject: '{{ template "custom_mail_subject" . }}'
        html: '{{ template "custom_mail_html" . }}'
        from: 'alice@example.com'
        smarthost: 'mail:25'
        hello: 'mail'
        auth_username: 'alice@example.com'
        auth_password: 'secretpassword'
        to: 'bopif57845@asuflex.com'