route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 1h
  receiver: 'mail'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
templates: 
  - '/alert_manager/*.tmpl'
receivers:
  - name: 'mail'
    email_configs:
      - require_tls: true
        headers: 
          subject: '{{ template "device_critical_subject" . }}'
        html: '{{ template "device_critical_html" . }}'
        from: 'camelcasecrew@gmail.com'
        smarthost: 'in-v3.mailjet.com:587'
        hello: 'localhost'
        auth_username: '7532e030a49b259cc62687cde8e2c047'
        auth_password: '404881b8a12010c4a7e0b70c220afa5a'
        to: 'camelcasecrew@gmail.com'